name: gldas-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - xarray
  - netcdf4
  - scipy
  - geopandas
  - shapely
  - pip
  - pip:
    - pytest
    - pytest-cov 